# **Import Libraries**

In [ ]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
import seaborn as sns

# **Mount Database From Google Drive**

In [ ]:
from google.colab import drive   # mount drive in google colab
drive.mount('/content/drive')

Mounted at /content/drive

# **Upload File in Google Colab**

In [ ]:
file_path='/content/drive/MyDrive/dataset/merged_medical_data.csv'  # upload database
df = pd.read_csv(file_path)   # Read file using pandas
df

,Gender,Disease,Glucose,Cholesterol,Hemoglobin,Platelets,White Blood Cells,Red Blood Cells,Hematocrit,Mean Corpuscular Volume,...,Triglycerides,HbA1c,LDL Cholesterol,HDL Cholesterol,ALT,AST,Heart Rate,Creatinine,Troponin,C-reactive Protein
0,Female,Healthy,126.133433,135.697821,17.223487,413126.659043,9633.481003,4.308518,40.112301,96.647243,...,102.038729,4.262777,94.413633,50.442121,15.021353,11.581306,74.124497,1.192936,0.030856,1.596364
1,Male,Liver Disease,73.076612,172.129506,14.380013,231268.420207,7935.663167,4.640516,40.330323,96.490459,...,56.520280,4.520946,76.787424,57.526713,73.418336,45.925814,81.824868,0.858017,0.013965,8.376125
2,Male,Liver Disease,88.990913,134.445934,14.007950,187658.874598,4738.452192,4.783822,48.188792,99.837856,...,147.221341,5.662226,96.326715,48.354164,43.857592,74.892397,72.178234,0.662849,0.013128,8.923041
3,Male,Hypercholesterolemia,81.433721,211.139585,15.633140,305052.014174,5007.593726,4.782938,48.181803,99.202799,...,159.887170,4.283218,197.321307,26.534159,17.922907,23.583538,92.310347,1.087095,0.027800,0.619570
4,Male,Liver Disease,78.649430,127.499634,17.116293,256392.808544,9380.790272,4.556660,50.100075,99.339765,...,86.092050,5.111424,107.699464,49.603548,54.851907,51.221055,78.347281,0.940594,0.029538,11.769606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349147,Male,Diabetes & Thalassemia & Anemia & Thrombocytop...,195.429648,283.571617,6.774627,90910.494038,5895.710504,3.301981,31.125314,68.959258,...,153.236683,8.434946,156.350440,32.855673,43.267858,51.551276,92.303219,3.949515,6.246726,9.184126
349148,Female,Diabetes & Thalassemia & Anemia & Thrombocytop...,192.904533,241.271032,7.459403,91886.849596,7423.406474,3.993353,34.686714,63.084707,...,202.124608,7.483220,138.705103,20.355824,46.100786,54.871108,100.319396,4.250698,9.767200,4.024387
349149,Female,Diabetes & Thalassemia & Anemia & Thrombocytop...,153.460912,248.549461,6.685512,105112.286240,8376.210372,3.192933,33.157727,67.634913,...,176.486043,11.893319,176.264933,20.965457,32.989377,39.858546,94.365884,1.976259,1.533946,3.546476
349150,Female,Diabetes & Thalassemia & Anemia & Thrombocytop...,160.192502,213.882117,8.938067,50117.113296,7994.611990,3.565482,25.963072,71.161767,...,172.085867,8.768746,141.181859,30.762153,45.856040,31.767431,104.236236,1.601472,2.456239,4.357553
349151,Female,Diabetes & Thalassemia & Anemia & Thrombocytop...,178.613869,271.780839,9.623506,105692.980021,7877.473670,3.194422,28.603093,70.626087,...,173.549280,9.560019,173.989834,33.094830,36.141325,41.060924,97.187869,4.360418,3.127092,8.979666

# **Getting data Information**

In [ ]:
df.info() # Getting database Information (Columns, Null Count, Rows Count, Datatype, Total Columns, Data Usage)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 349152 entries, 0 to 349151
Data columns (total 26 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Gender                                     349152 non-null  object
 1   Disease                                    349152 non-null  object
 2   Glucose                                    349152 non-null  float64
 3   Cholesterol                                349152 non-null  float64
 4   Hemoglobin                                 349152 non-null  float64
 5   Platelets                                  349152 non-null  float64
 6   White Blood Cells                          349152 non-null  float64
 7   Red Blood Cells                            349152 non-null  float64
 8   Hematocrit                                 349152 non-null  float64
 9   Mean Corpuscular Volume                    349152 non-null  float64
 10  Mean Corpuscular Hemoglobin                349152 non-null  float64
 11  Mean Corpuscular Hemoglobin Concentration  349152 non-null  float64
 12  Insulin                                    349152 non-null  float64
 13  BMI                                        349152 non-null  float64
 14  Systolic Blood Pressure                    349152 non-null  float64
 15  Diastolic Blood Pressure                   349152 non-null  float64
 16  Triglycerides                              349152 non-null  float64
 17  HbA1c                                      349152 non-null  float64
 18  LDL Cholesterol                            349152 non-null  float64
 19  HDL Cholesterol                            349152 non-null  float64
 20  ALT                                        349152 non-null  float64
 21  AST                                        349152 non-null  float64
 22  Heart Rate                                 349152 non-null  float64
 23  Creatinine                                 349152 non-null  float64
 24  Troponin                                   349152 non-null  float64
 25  C-reactive Protein                         349152 non-null  float64
dtypes: float64(24), object(2)
memory usage: 69.3+ MB

# **Checking Null Values**

In [ ]:
df.isna().sum()   # Getting Count of Null Values of all the Columns

Gender                                       0
Disease                                      0
Glucose                                      0
Cholesterol                                  0
Hemoglobin                                   0
Platelets                                    0
White Blood Cells                            0
Red Blood Cells                              0
Hematocrit                                   0
Mean Corpuscular Volume                      0
Mean Corpuscular Hemoglobin                  0
Mean Corpuscular Hemoglobin Concentration    0
Insulin                                      0
BMI                                          0
Systolic Blood Pressure                      0
Diastolic Blood Pressure                     0
Triglycerides                                0
HbA1c                                        0
LDL Cholesterol                              0
HDL Cholesterol                              0
ALT                                          0
AST                                          0
Heart Rate                                   0
Creatinine                                   0
Troponin                                     0
C-reactive Protein                           0
dtype: int64